[build]
  publish = "public"
  command = "# no build command"

[[redirects]]
  from = "/api/*"
  to = "https://chatrio-production.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept", Access-Control-Allow-Credentials = "true"}

[[redirects]]
  from = "/socket.io/*"
  to = "https://chatrio-production.up.railway.app/socket.io/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept", Access-Control-Allow-Credentials = "true"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"
    Cache-Control = "no-store, no-cache" 