[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node server/server.js"
healthcheckPath = "/api/auth/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 